### ISSUE TITLE
Is there caching involved?

### ISSUE THREAD

**Issue by vectronic** [cloudydeno/module-visualizer#6]
Hello,

I have just started to use this service - nice work!

I am wondering if there is a caching mechanism in place and how long expiry is set to?

When I look here:

https://deno-visualizer.danopia.net/dependencies-of/https/raw.githubusercontent.com/flowscripter/template-deno-executable/main/mod.ts

it seems to be out of date compared to the deps file which ends up being loaded here:

https://raw.githubusercontent.com/flowscripter/template-deno-executable/main/deps.ts

Or is this HTTP cache headers coming from raw.githubusercontent.com which is getting in the way?

Any help or advice appreciated.

Thanks again,
Nick

**Comment by vectronic** [comment]
I'll close this as the info is now updated (about 3 hours later). So there is some kind of caching or eventual consistency happening somewhere. But at least I know it is in the order of hours.

Sorry for the noise then... and thanks again.

**Comment by danopia** [comment]
Hello, thanks for your interest :)

Yes there is some degree of caching. Actually, the caching is what Deno itself implements - if you run `deno run` on the same URL multiple times, it doesn't redownload the URL each time unless `--reload` is passed. Deno wants the same URL to always resolve to the same data.

As a workaround, replace 'main' with a specific githash to make sure you are visualizing the dependencies as-of a specific commit. For example: https://deno-visualizer.danopia.net/dependencies-of/https/raw.githubusercontent.com/flowscripter/template-deno-executable/6c67ada45ebcbbb21ec0784a6a7d0dd2fc316431/mod.ts

Because the deno cache is stored on a temporary filesystem, it will be disposed when the app goes idle (more than maybe ~15 minutes without activity, but not well defined). While the app is being actively used the cache will stay in place.

This is currently undocumented so I'll address the lack of documentation before closing. (editor's note - oops too slow)

Cheers
